blank_issues_enabled: false
contact_links:
  - name: Security Vulnerabilities
    url: https://khulnasoft.com/security
    about: >
      Please report security vulnerabilities privately via email to security@khulnasoft.com.
